import fs from 'fs';

const lines = [];
const push = s => lines.push(s);
const hr = () => push('\n---\n');

// ─── HEADER ───
push('# DSA Learning Document');
push('');
push('> A comprehensive, student-friendly guide to Data Structures & Algorithms.');
push('> Master the fundamentals with clear explanations, real-world analogies, and practical code.');
push('');
push('---\n');

// ─── TOC ───
push('## Table of Contents');
push('');
push('1. [Introduction to DSA](#1-introduction-to-dsa)');
push('   - [What is DSA?](#11-what-is-dsa)');
push('   - [Time Complexity](#12-time-complexity)');
push('   - [Space Complexity](#13-space-complexity)');
push('   - [Big O / Ω / Θ Notation](#14-big-o--ω--θ-notation)');
push('2. [Arrays](#2-arrays)');
push('   - [Array Basics](#21-array-basics)');
push('   - [Two Pointers](#22-two-pointers)');
push('   - [Sliding Window](#23-sliding-window)');
push('   - [Prefix Sum](#24-prefix-sum)');
push('');
push('---\n');

// ═══════════════════════════════════════════════════
// SECTION 1: INTRODUCTION TO DSA
// ═══════════════════════════════════════════════════
push('# 1. Introduction to DSA');
push('');
push('> **Lesson Overview:** Start here — understand what DSA actually is, why it matters, and how to measure how "good" a solution is before touching a coding problem.');
push('> - **Category:** Fundamentals: Arrays & Strings');
push('> - **Difficulty:** Easy');
push('> - **Problems:** 3');
push('');
hr();

// --- 1.1 What is DSA? ---
push('## 1.1 What is DSA?');
push('');
push('### What is a Data Structure?');
push('');
push('A **Data Structure** is a way of organizing and storing data so it can be used efficiently. It\'s not a programming concept invented in isolation — it mirrors how we organize things in real life.');
push('');
push('Think about a library. Books aren\'t just piled randomly; they\'re arranged by genre, then author, then title. That arrangement is a "data structure" for books — it determines how fast you can find what you\'re looking for. A messy pile might still contain the same books, but finding one would take forever.');
push('');
push('In programming, the "books" are your data — numbers, names, records — and the data structure is how that data sits in memory. Common examples you\'ll learn in this course:');
push('');
push('- **Arrays** — items stored back-to-back, like seats in a row');
push('- **Linked Lists** — items connected by pointers, like a treasure hunt where each clue points to the next');
push('- **Stacks** — items stacked on top of each other, like a pile of plates (last one placed is first one removed)');
push('- **Queues** — items in a line, like people waiting at a ticket counter (first in line is first served)');
push('- **Trees and Graphs** — items connected in branching or networked relationships, like a family tree or a map of cities connected by roads');
push('');
push('### What is an Algorithm?');
push('');
push('An **algorithm** is a precise, step-by-step procedure for solving a problem. You already use algorithms every day without calling them that:');
push('');
push('- A recipe is an algorithm for cooking a dish.');
push('- Directions from a maps app are an algorithm for reaching a destination.');
push('- The process of alphabetizing your bookshelf is a sorting algorithm.');
push('');
push('In programming, an algorithm takes some input, follows a defined sequence of steps, and produces an output — reliably, every time, for any valid input. "Find the largest number in this list" is a problem; the loop you write to solve it is the algorithm.');
push('');
push('### Why Study Them Together?');
push('');
push('Data structures and algorithms aren\'t separate subjects — they\'re deeply connected, because the data structure you choose determines what algorithms are possible and how fast they\'ll run.');
push('');
push('For example:');
push('');
push('- Searching for a word in a dictionary (sorted list) can use **binary search** — O(log n).');
push('- Searching for a word in a messy pile (unsorted list) requires checking every page — O(n).');
push('');
push('The data is the same, but the data structure is different, and that changes everything.');
push('');
push('### Key Takeaway');
push('');
push('DSA is the foundation of writing code that doesn\'t just work, but works efficiently. Companies test DSA in interviews not because they want you to reinvent every algorithm from scratch, but because DSA skills predict whether you can write code that scales — code that handles 10 users just as smoothly as 10 million.');
push('');
hr();

// --- 1.2 Time Complexity ---
push('## 1.2 Time Complexity');
push('');
push('### Why We Measure Time This Way');
push('');
push('You can\'t measure an algorithm\'s speed in seconds — the same code runs faster on a gaming laptop than on a five-year-old phone. So instead of measuring actual time, we measure **how the number of operations grows as the input size (usually called n) grows**. This gives us a measurement that\'s true regardless of hardware, programming language, or how fast the machine running it happens to be.');
push('');
push('This growth pattern is called **Time Complexity**, and we describe it using **Big O notation** — O() — which represents the worst-case growth rate.');
push('');
push('### Building Intuition With an Example');
push('');
push('Say you have a list of n numbers and you want to check if a target number exists in it.');
push('');
push('**Approach 1 — Check every number one at a time.**');
push('If the list has 10 numbers, worst case you check all 10. If it has 10 million numbers, worst case you check all 10 million. The number of checks grows exactly in step with the size of the list. We call this **Linear Time — O(n)**.');
push('');
push('**Approach 2 — If the list is sorted, use binary search:**');
push('Check the middle element, and depending on whether your target is bigger or smaller, discard half the list and repeat.');
push('For 10 million numbers, this takes only about 24 steps (2^24 is roughly 16 million) — because you\'re cutting the problem in half every single time. We call this **Logarithmic Time — O(log n)**.');
push('');
push('Same task, same data — but a completely different growth rate depending on the approach.');
push('');
push('### The Complexity Classes You\'ll See Constantly');
push('');
push('Here they are ranked from fastest-growing (best) to slowest-growing (worst):');
push('');
push('| Class | Name | Example | Growth for n=1000 |');
push('|---|---|---|---|');
push('| O(1) | Constant | Access arr[5] | 1 operation |');
push('| O(log n) | Logarithmic | Binary search | ~10 operations |');
push('| O(n) | Linear | Single loop | 1000 operations |');
push('| O(n log n) | Linearithmic | Merge sort | ~10,000 operations |');
push('| O(n²) | Quadratic | Nested loops | 1,000,000 operations |');
push('| O(2^n) | Exponential | Fibonacci recursion | ~10^301 operations |');
push('');
push('### How to Find Time Complexity in 3 Steps');
push('');
push('1. **Find the loops** — each loop that runs n times adds a factor of n.');
push('2. **Check nesting** — nested loops multiply: two nested loops = n × n = n².');
push('3. **Drop constants and lower terms** — O(2n + 100) becomes O(n). Only the fastest-growing term matters for large n.');
push('');
push('```text');
push('FUNCTION example(arr):');
push('    FOR i FROM 0 TO length(arr)-1:    # O(n)');
push('        print(arr[i])                  # O(1) inside');
push('    # Total: O(n × 1) = O(n)');
push('```');
push('');
push('### Key Takeaway');
push('');
push('Time complexity is about **growth rate**, not actual speed. O(n) code on a supercomputer will eventually lose to O(log n) code on a cheap phone — once n is large enough. Always think: "What happens when n doubles?"');
push('');
hr();

// --- 1.3 Space Complexity ---
push('## 1.3 Space Complexity');
push('');
push('### What Space Complexity Actually Measures');
push('');
push('**Space Complexity** measures how much extra memory an algorithm needs as the input size grows — using the same Big O notation you just learned for time. Just like time complexity isn\'t measured in literal seconds, space complexity isn\'t measured in literal megabytes; it\'s measured in **how memory usage scales as n grows**.');
push('');
push('It\'s important to separate two things:');
push('');
push('- **Input space** — the memory needed just to store the data you were given. This is usually not counted against your algorithm.');
push('- **Auxiliary space** — any extra memory your algorithm uses while it runs: temporary variables, new arrays or objects you create, or the hidden memory used by recursive function calls.');
push('');
push('When people say "what\'s the space complexity of this algorithm?" — in interviews and in this course — they almost always mean **auxiliary space**.');
push('');
push('### A Simple Comparison: In-Place vs Creating New Memory');
push('');
push('Say you want to reverse an array of n elements.');
push('');
push('**Approach 1 — Swap elements in place**');
push('Swap the first and last, then the second and second-last, and so on.');
push('You only ever need a couple of temporary variables — regardless of whether the array has 10 or 10 million elements.');
push('This is **Constant Space — O(1)**.');
push('');
push('**Approach 2 — Create a brand new array**');
push('Copy elements into it in reverse order.');
push('The size of this new array grows directly with the input size.');
push('This is **Linear Space — O(n)**.');
push('');
push('Both approaches solve the same problem correctly and both run in O(n) time — but they have very different space complexity.');
push('');
push('### Common Space Complexities');
push('');
push('| Class | Name | Example |');
push('|---|---|---|');
push('| O(1) | Constant | A few variables (counters, pointers) |');
push('| O(n) | Linear | An array of size n, or a hash map storing n entries |');
push('| O(n²) | Quadratic | An n×n matrix |');
push('');
push('### The Hidden Cost: Recursion Stack');
push('');
push('Every time a function calls itself recursively, the computer needs to remember where to "return to" once that call finishes. This information is stored on the **call stack**, and it counts toward space complexity.');
push('');
push('For example, a recursive function that calls itself n times before returning has O(n) space complexity — even if it doesn\'t create any new arrays — because the call stack itself grows to n levels deep.');
push('');
push('### Key Takeaway');
push('');
push('Always ask: "Does this algorithm create new memory that grows with the input?" If yes, that\'s linear or worse space. If you\'re reusing the existing data structure and only using a few extra variables, that\'s constant space.');
push('');
hr();

// --- 1.4 Big O / Ω / Θ ---
push('## 1.4 Big O / Ω / Θ Notation');
push('');
push('### Beyond "Just" Big O');
push('');
push('So far you\'ve been using Big O informally — the idea that O(n) means "roughly proportional to n." Now let\'s make this precise, because Big O is actually one of **three related notations**, and knowing the difference will sharpen your understanding of algorithm analysis.');
push('');
push('Each notation describes a boundary on how an algorithm\'s running time (or space) behaves as input size grows — but each one describes a **different kind of boundary**.');
push('');
push('### Big O (O) — The Upper Bound (Worst Case)');
push('');
push('Big O describes the **maximum** amount of time an algorithm could possibly take. It answers: "No matter how unlucky the input is, the algorithm will never take longer than this."');
push('');
push('This is why Big O is used almost everywhere — it\'s a **guarantee**. If someone tells you "this runs in O(n²)," they\'re telling you the absolute ceiling: it will never behave worse than that.');
push('');
push('### Big Omega (Ω) — The Lower Bound (Best Case)');
push('');
push('Big Omega describes the **minimum** amount of time an algorithm could take — the best possible scenario. It answers: "Even in the best case, the algorithm can\'t do better than this."');
push('');
push('**Example:** Linear Search has a best case of Ω(1) — if the very first element you check happens to be the target, you\'re done in one step.');
push('');
push('### Big Theta (Θ) — The Tight Bound');
push('');
push('Big Theta is used when an algorithm\'s best-case and worst-case are the **same** growth rate — meaning there\'s no variance depending on the input. It answers: "This algorithm always behaves this way, regardless of input."');
push('');
push('**Example:** Finding the maximum value in an unsorted array — you must check every element, no shortcuts. Best case = O(n), worst case = O(n), so it\'s Θ(n).');
push('');
push('### Visual Comparison');
push('');
push('```');
push('      Time');
push('       ↑');
push('       |    ╱ O(n) — Upper bound (worst case)');
push('       |   ╱');
push('       |  ╱  Θ(n) — Tight bound');
push('       | ╱');
push('       |╱  Ω(1) — Lower bound (best case)');
push('       └──────────────────→ Input size');
push('```');
push('');
push('### Practical Advice');
push('');
push('- In interviews and this course, **Big O is what matters most**. Interviewers want to know the worst-case guarantee.');
push('- Ω and Θ are useful in academic contexts and when analyzing algorithms that have no variance.');
push('- When someone says "Big O of n," they usually mean Θ(n) — the typical case — unless they\'re being very precise.');
push('');
push('### Key Takeaway');
push('');
push('Big O = worst case (ceiling). Big Omega = best case (floor). Big Theta = tight bound (both are the same). For most practical purposes, focus on Big O — it\'s the guarantee your code won\'t surprise you.');
push('');
hr();

// ═══════════════════════════════════════════════════
// SECTION 2: ARRAYS
// ═══════════════════════════════════════════════════
push('# 2. Arrays');
push('');
push('> **Lesson Overview:** Arrays are the most fundamental data structure in programming. Learn how they work in memory, how to manipulate them, and three essential problem-solving techniques.');
push('> - **Category:** Fundamentals: Arrays & Strings');
push('> - **Difficulty:** Easy');
push('> - **Problems:** 4');
push('');
hr();

// --- 2.1 Array Basics ---
push('## 2.1 Array Basics');
push('');
push('### What is an Array?');
push('');
push('Imagine a row of lockers in a school hallway. Each locker has a number painted on it — 0, 1, 2, 3, and so on. You know exactly where locker 14 is: it\'s the 15th locker from the start. You don\'t have to count — you walk straight to it because the lockers are arranged in a straight line and every locker takes up the same amount of space.');
push('');
push('An array is exactly like that row of lockers — it\'s a **contiguous block of memory** divided into equally-sized slots, each identified by an index starting from 0.');
push('');
push('### How Arrays Work in Memory');
push('');
push('When you create an array like `[10, 20, 30, 40]`, the computer finds a free block of memory large enough to hold four numbers and places them one right after the other:');
push('');
push('```');
push('Memory:  [10] [20] [30] [40]');
push('Address: 100  104  108  112');
push('Index:     0    1    2    3');
push('```');
push('');
push('If each integer takes 4 bytes, the address of element at index `i` is:');
push('');
push('```');
push('address = base_address + (i x size_of_each_element)');
push('```');
push('');
push('This is why array access is O(1) — the computer can calculate the exact memory address in a single step.');
push('');
push('### Common Operations and Their Time Complexity');
push('');
push('| Operation | Time | Explanation |');
push('|---|---|---|');
push('| Access by index | O(1) | Direct calculation of memory address |');
push('| Search for a value | O(n) | May need to check every element |');
push('| Insert at end (dynamic) | O(1) amortized | Usually one step, occasional copy |');
push('| Insert at beginning/middle | O(n) | All elements must shift |');
push('| Delete from end | O(1) | Just remove the last element |');
push('| Delete from beginning/middle | O(n) | All elements must shift |');
push('');
push('### Static vs Dynamic Arrays');
push('');
push('- **Static arrays:** Fixed size set at creation. Can\'t add more elements than capacity.');
push('- **Dynamic arrays** (Python lists, JavaScript arrays): Automatically grow when full by allocating a larger block and copying elements over. This doubling strategy makes most insertions O(1), with an occasional O(n) copy.');
push('');
push('### Array Operations in Pseudocode');
push('');
push('```text');
push('# Access element at index i');
push('FUNCTION access(arr, i):');
push('    RETURN arr[i]   # O(1)');
push('');
push('# Search for a value');
push('FUNCTION search(arr, target):');
push('    FOR i FROM 0 TO length(arr)-1:');
push('        IF arr[i] == target:');
push('            RETURN i');
push('    RETURN -1        # O(n)');
push('');
push('# Insert at the end');
push('FUNCTION insert_end(arr, value):');
push('    arr[length(arr)] = value   # O(1) amortized');
push('```');
push('');
push('### When to Use Arrays');
push('');
push('✅ **Fast access by index** — arr[i] is always O(1)');
push('✅ **You know roughly how many items you\'ll store**');
push('✅ **You iterate through items sequentially**');
push('✅ **Memory overhead matters** — arrays are the most memory-efficient structure for sequences');
push('');
push('❌ **Frequent insert/delete at beginning** — use a deque or linked list');
push('❌ **Frequent value-based search** — use a hash table or BST');
push('');
push('### Key Takeaway');
push('');
push('Arrays\' superpower is O(1) index access; their weakness is O(n) insertion/deletion anywhere except the end. The three techniques you\'ll learn next — Two Pointers, Sliding Window, and Prefix Sum — are all about working around this weakness.');
push('');
hr();

// --- 2.2 Two Pointers ---
push('## 2.2 Two Pointers');
push('');
push('### What is the Two-Pointer Technique?');
push('');
push('Imagine you and a friend are standing at opposite ends of a long hallway lined with numbered boxes. You both walk toward each other, checking boxes as you go. Between the two of you, you can cover the entire hallway in one pass, meeting somewhere in the middle.');
push('');
push('That\'s the two-pointer technique: instead of using a single loop variable, you use **two indices** (pointers) that move through the array, often from opposite ends toward each other. This lets you solve problems in O(n) time that would otherwise require O(n²) with nested loops.');
push('');
push('### The Two Main Patterns');
push('');
push('**1. Opposite Direction (Left/Right)**');
push('');
push('Both pointers start at opposite ends and move toward each other:');
push('');
push('```');
push('[1, 3, 5, 7, 9]');
push(' ^             ^');
push('left         right');
push('```');
push('');
push('After each step, either `left` moves right or `right` moves left, depending on some condition. The pointers meet (or cross) in the middle.');
push('');
push('**Example problem:** Given a sorted array, find two numbers that add up to a target.');
push('');
push('**2. Same Direction (Fast/Slow)**');
push('');
push('Both pointers start at the same end, but one moves faster than the other. Useful for finding cycles, removing duplicates, or finding the middle of a linked list.');
push('');
push('### Why Two Pointers Work');
push('');
push('Nested loops check every possible pair — a classic O(n²) approach:');
push('');
push('```text');
push('FOR i FROM 0 TO n-1:');
push('    FOR j FROM i+1 TO n-1:');
push('        # check pair (i, j)');
push('```');
push('');
push('Two pointers eliminate the inner loop by using the fact that **the data is structured** (often sorted). Once a pointer moves past a certain point, those elements are no longer relevant.');
push('');
push('### Concrete Example');
push('');
push('Find two numbers in sorted `[1, 3, 4, 6, 8, 10]` that sum to 12:');
push('');
push('```');
push('Step 1: left=0(1), right=5(10) → sum=11 → too small, move left');
push('Step 2: left=1(3), right=5(10) → sum=13 → too big, move right');
push('Step 3: left=1(3), right=4(8)  → sum=11 → too small, move left');
push('Step 4: left=2(4), right=4(8)  → sum=12 → found!');
push('```');
push('');
push('4 steps instead of 15. For n=1000: ~999 steps instead of ~500,000.');
push('');
push('### When to Use Two Pointers');
push('');
push('✅ The array is sorted');
push('✅ You need to find a pair (or triplet) that satisfies a condition');
push('✅ You need to reverse or rotate in place');
push('✅ The problem involves partitioning or rearranging elements');
push('');
push('### Complexity');
push('- **Time:** O(n) — each pointer moves at most n times');
push('- **Space:** O(1) — only two variables for the indices');
push('');
push('### Key Takeaway');
push('');
push('The two-pointer technique is your first tool for moving from O(n²) to O(n). Whenever you see a problem involving arrays (especially sorted ones) and pairs, ask: "Can I use two pointers here?"');
push('');
hr();

// --- 2.3 Sliding Window ---
push('## 2.3 Sliding Window');
push('');
push('### What is a Sliding Window?');
push('');
push('Imagine you\'re looking through a train window as the train moves. At any moment, you see a specific stretch of the landscape — that\'s your "window." As the train moves, the window slides, revealing new scenery on one side and losing old scenery on the other. You never re-examine the entire journey at once — just the part visible through the window.');
push('');
push('A **sliding window** in programming is the same idea: it\'s a contiguous subarray that moves across the array one element at a time, or expands and contracts based on conditions. Instead of restarting from scratch for every subarray, you **reuse** the computation from the previous window.');
push('');
push('### Fixed Window vs Variable Window');
push('');
push('**Fixed Window Size:**');
push('');
push('```');
push('Array: [2, 5, 1, 8, 3, 7], k = 3');
push('');
push('Window 1: [2, 5, 1] → sum = 8');
push('Window 2: [5, 1, 8] → sum = 14  (added 8, removed 2)');
push('Window 3: [1, 8, 3] → sum = 12  (added 3, removed 5)');
push('Window 4: [8, 3, 7] → sum = 18  (added 7, removed 1)');
push('```');
push('');
push('Notice: instead of summing all three elements each time, just **add the new element** and **subtract the element that left**. That\'s O(1) per slide instead of O(k).');
push('');
push('**Variable Window Size:**');
push('');
push('The window grows or shrinks based on a condition (like "sum >= target" or "all unique characters"):');
push('');
push('```text');
push('Start with both pointers at index 0');
push('Expand right pointer until condition is met');
push('Contract left pointer until condition is broken');
push('Repeat until right pointer reaches the end');
push('```');
push('');
push('### Why Sliding Windows Work');
push('');
push('Brute force checks every possible subarray — O(n²) subarrays:');
push('');
push('```text');
push('FOR i FROM 0 TO n-1:');
push('    FOR j FROM i TO n-1:');
push('        # consider subarray arr[i..j]');
push('```');
push('');
push('The key insight: **contiguous subarrays that start at different positions are highly overlapping**. Most elements in arr[i..j] are also in arr[i+1..j+1]. Just adjust for what entered and left instead of recalculating from scratch.');
push('');
push('### When to Use Sliding Window');
push('');
push('✅ The problem involves a contiguous subarray or substring');
push('✅ You need to find a subarray that satisfies a condition (max, min, longest, shortest)');
push('✅ The problem mentions "subarray" or "substring"');
push('');
push('### Complexity');
push('- **Time:** O(n) — each element enters and leaves the window at most once');
push('- **Space:** O(1) or O(k) depending on what you store in the window');
push('');
push('### Key Takeaway');
push('');
push('Whenever you read "contiguous subarray" or "substring" in a problem, your first thought should be: "Can I use a sliding window?" It turns O(n²) brute-force into clean, O(n) code.');
push('');
hr();

// --- 2.4 Prefix Sum ---
push('## 2.4 Prefix Sum');
push('');
push('### What is Prefix Sum?');
push('');
push('Imagine you\'re a teacher grading quizzes. A student asks, "What\'s my total on questions 5 through 12?" You could add those 8 questions individually — 8 additions per question. If 30 students ask, you\'re doing hundreds of additions.');
push('');
push('A smarter way: before class, compute a **running total** as you go through the answer key. After question 1, write the subtotal. After question 2, write the new subtotal. Now when a student asks about questions 5-12, you just look up the total through question 12 and subtract the total through question 4. Two lookups, one subtraction — done.');
push('');
push('That\'s the prefix sum technique.');
push('');
push('### How It Works');
push('');
push('Given an array `arr`, the prefix sum array `prefix` is:');
push('');
push('```');
push('prefix[0] = 0');
push('prefix[i] = sum of arr[0] + arr[1] + ... + arr[i-1]');
push('```');
push('');
push('Example:');
push('');
push('```');
push('arr    = [3,  1,  4,  1,  5,  9,  2]');
push('prefix = [0,  3,  4,  8,  9, 14, 23, 25]');
push('index    0   1   2   3   4   5   6   7');
push('```');
push('');
push('To build:');
push('- prefix[0] = 0');
push('- prefix[1] = prefix[0] + arr[0] = 0 + 3 = 3');
push('- prefix[2] = prefix[1] + arr[1] = 3 + 1 = 4');
push('- ... and so on');
push('');
push('### The Magic Formula: Range Sum in O(1)');
push('');
push('To get the sum from index `l` to `r` (inclusive):');
push('');
push('```');
push('sum(l, r) = prefix[r + 1] - prefix[l]');
push('```');
push('');
push('Why? prefix[r+1] is sum of indices 0 to r. prefix[l] is sum of indices 0 to l-1. Subtract them and you get elements l through r.');
push('');
push('Example: sum of indices 2 to 5:');
push('- prefix[6] = 23 (sum of indices 0-5)');
push('- prefix[2] = 4 (sum of indices 0-1)');
push('- 23 - 4 = 19 = 4 + 1 + 5 + 9 ✅');
push('');
push('### The Space-Time Tradeoff');
push('');
push('| Approach | Query Time | Memory |');
push('|---|---|---|');
push('| Without prefix sum | O(n) per query | O(1) |');
push('| With prefix sum | O(1) per query | O(n) for the array |');
push('');
push('This tradeoff is worth it when you need to answer **many** range sum queries on the **same** array.');
push('');
push('### Beyond Sums');
push('');
push('The prefix idea extends to any **reversible** operation: prefix products, prefix XORs, prefix counts. XOR is particularly useful because it\'s its own inverse (a XOR a = 0).');
push('');
push('### Deeper Application: Subarray Sum Equals K');
push('');
push('Combining prefix sums with a hash map lets you count subarrays that sum to exactly k in O(n) time:');
push('');
push('```text');
push('FUNCTION subarray_sum(arr, k):');
push('    prefix_map = {0: 1}');
push('    prefix_sum = 0');
push('    count = 0');
push('');
push('    FOR EACH num IN arr:');
push('        prefix_sum = prefix_sum + num');
push('        IF (prefix_sum - k) IN prefix_map:');
push('            count = count + prefix_map[prefix_sum - k]');
push('        prefix_map[prefix_sum] = prefix_map[prefix_sum] + 1');
push('');
push('    RETURN count');
push('```');
push('');
push('The key insight: if (current_prefix - k) has appeared before, then a subarray ending at the current position sums to k.');
push('');
push('### When to Use Prefix Sum');
push('');
push('✅ You need to answer many range sum queries on the same array');
push('✅ You need to find subarrays with a specific sum');
push('✅ The problem involves cumulative or running totals');
push('✅ Operations are reversible (addition, subtraction, XOR)');
push('');
push('### Complexity');
push('- **Precomputation:** O(n) — one pass');
push('- **Each query:** O(1) — one subtraction');
push('- **Space:** O(n) for the prefix array');
push('');
push('### Key Takeaway');
push('');
push('Prefix sum is a preprocessing technique that makes range sum queries instant. Whenever you need sums of multiple subarrays, think: "Can I precompute prefix sums and answer each query in O(1)?"');
push('');
hr();

// ═══════════════════════════════════════════════════
// SECTION 3: PROBLEMS
// ═══════════════════════════════════════════════════
push('# 3. Practice Problems');
push('');
push('This section contains all problems with detailed solutions. Each problem includes the statement, examples, approach walkthrough, and code in Python and JavaScript.');
push('');
hr();

// --- Problem 1: Reverse an Array ---
push('## 3.1 Reverse an Array');
push('');
push('| | |');
push('|---|---|');
push('| **Difficulty** | Easy |');
push('| **Subtopic** | Array Basics |');
push('| **Companies** | Amazon, Google, Microsoft, Apple |');
push('');
push('### Problem Statement');
push('');
push('You are given an array of numbers. Reverse the order of its elements **in-place** — modify the original array directly, without creating a separate copy.');
push('');
push('```');
push('Input:  [1, 2, 3, 4, 5]');
push('Output: [5, 4, 3, 2, 1]');
push('```');
push('');
push('### Examples');
push('');
push('| Input | Output | Explanation |');
push('|---|---|---|');
push('| [1, 2, 3, 4, 5] | [5, 4, 3, 2, 1] | Swap 0↔4, then 1↔3 |');
push('| [7, 8, 9] | [9, 8, 7] | Swap 0↔2 |');
push('| [42] | [42] | Single element, already reversed |');
push('| [] | [] | Empty array |');
push('');
push('### Constraints');
push('- 0 to 100,000 elements');
push('- Each element: -10⁹ to 10⁹');
push('');
push('### Approach');
push('');
push('**Step 1 — The naive way:** Create a new array and copy elements in reverse. Works but uses O(n) extra memory — doesn\'t meet the in-place requirement.');
push('');
push('**Step 2 — Two-pointer approach (optimal):**');
push('');
push('1. Place `left` at index 0 and `right` at the last index.');
push('2. Swap the elements at these two positions.');
push('3. Move `left` right by 1, move `right` left by 1.');
push('4. Repeat until `left` >= `right`.');
push('');
push('```');
push('Initial:     [1, 2, 3, 4, 5]');
push('              L              R');
push('');
push('After swap:  [5, 2, 3, 4, 1]');
push('                 L        R');
push('');
push('After swap:  [5, 4, 3, 2, 1]');
push('                    L');
push('                    R');
push('Pointers meet — done!');
push('```');
push('');
push('**Why this works:** Each swap places two elements in their correct final position. After the first swap, positions 0 and n-1 are final — we never need to touch them again.');
push('');
push('```text');
push('FUNCTION reverse_array(arr):');
push('    left = 0');
push('    right = length(arr) - 1');
push('');
push('    WHILE left < right:');
push('        SWAP arr[left], arr[right]');
push('        left = left + 1');
push('        right = right - 1');
push('');
push('    RETURN arr');
push('```');
push('');
push('**Complexity:**');
push('- Time: O(n) — n/2 swaps');
push('- Space: O(1) — just two variables');
push('');
push('### Code Solution');
push('');
push('```python');
push('def reverse_array(arr):');
push('    left = 0');
push('    right = len(arr) - 1');
push('');
push('    while left < right:');
push('        arr[left], arr[right] = arr[right], arr[left]');
push('        left += 1');
push('        right -= 1');
push('');
push('    return arr');
push('```');
push('');
push('```javascript');
push('function reverseArray(arr) {');
push('    let left = 0;');
push('    let right = arr.length - 1;');
push('');
push('    while (left < right) {');
push('        [arr[left], arr[right]] = [arr[right], arr[left]];');
push('        left++;');
push('        right--;');
push('    }');
push('');
push('    return arr;');
push('}');
push('```');
push('');
hr();

// --- Problem 2: Two Sum (Sorted Array) ---
push('## 3.2 Two Sum (Sorted Array)');
push('');
push('| | |');
push('|---|---|');
push('| **Difficulty** | Easy |');
push('| **Subtopic** | Two Pointers |');
push('| **Companies** | Amazon, Google, Microsoft, Facebook |');
push('');
push('### Problem Statement');
push('');
push('Given a **sorted** array of numbers and a target, find two numbers that add up to exactly the target. Return their 0-based indices. You may not use the same element twice.');
push('');
push('```');
push('Input:  arr = [2, 7, 11, 15], target = 9');
push('Output: [0, 1]  (because 2 + 7 = 9)');
push('```');
push('');
push('### Examples');
push('');
push('| Input | Output | Explanation |');
push('|---|---|---|');
push('| [2, 7, 11, 15], target=9 | [0, 1] | 2 + 7 = 9 |');
push('| [1, 3, 4, 5, 7, 10], target=8 | [2, 3] | 4 + 5 = 8 |');
push('| [1, 2, 3], target=10 | [] | No pair sums to 10 |');
push('');
push('### Constraints');
push('- 2 to 100,000 elements');
push('- Sorted in strictly increasing order');
push('- At most one valid pair exists');
push('');
push('### Approach');
push('');
push('**Brute force:** Check every pair — O(n²). For 100,000 elements, that\'s 5 billion pairs.');
push('');
push('**Two-pointer solution (optimal):**');
push('');
push('Since the array is sorted, we can use this logic:');
push('- If the sum of left + right is **too small**, we need a bigger left element (move left right).');
push('- If the sum is **too big**, we need a smaller right element (move right left).');
push('');
push('```text');
push('FUNCTION two_sum_sorted(arr, target):');
push('    left = 0');
push('    right = length(arr) - 1');
push('');
push('    WHILE left < right:');
push('        current_sum = arr[left] + arr[right]');
push('');
push('        IF current_sum == target:');
push('            RETURN [left, right]');
push('        ELSE IF current_sum < target:');
push('            left = left + 1');
push('        ELSE:');
push('            right = right - 1');
push('');
push('    RETURN []');
push('```');
push('');
push('**Why this works:** Every step eliminates one entire row of possibilities. When sum < target, arr[left] + ANY element to the right would be too small, so we can safely skip arr[left].');
push('');
push('**Complexity:**');
push('- Time: O(n)');
push('- Space: O(1)');
push('');
push('### Code Solution');
push('');
push('```python');
push('def two_sum_sorted(arr, target):');
push('    left = 0');
push('    right = len(arr) - 1');
push('');
push('    while left < right:');
push('        current_sum = arr[left] + arr[right]');
push('');
push('        if current_sum == target:');
push('            return [left, right]');
push('        elif current_sum < target:');
push('            left += 1');
push('        else:');
push('            right -= 1');
push('');
push('    return []');
push('```');
push('');
push('```javascript');
push('function twoSumSorted(arr, target) {');
push('    let left = 0;');
push('    let right = arr.length - 1;');
push('');
push('    while (left < right) {');
push('        const currentSum = arr[left] + arr[right];');
push('');
push('        if (currentSum === target) {');
push('            return [left, right];');
push('        } else if (currentSum < target) {');
push('            left++;');
push('        } else {');
push('            right--;');
push('        }');
push('    }');
push('');
push('    return [];');
push('}');
push('```');
push('');
hr();

// --- Problem 3: Longest Substring Without Repeating Characters ---
push('## 3.3 Longest Substring Without Repeating Characters');
push('');
push('| | |');
push('|---|---|');
push('| **Difficulty** | Medium |');
push('| **Subtopic** | Sliding Window |');
push('| **Companies** | Amazon, Google, Microsoft, Facebook, Apple |');
push('');
push('### Problem Statement');
push('');
push('Given a string, find the length of the **longest contiguous substring** that contains no repeating characters.');
push('');
push('```');
push('Input:  "abcabcbb"');
push('Output: 3  (the substring "abc")');
push('```');
push('');
push('### Examples');
push('');
push('| Input | Output | Explanation |');
push('|---|---|---|');
push('| "abcabcbb" | 3 | "abc", "bca", or "cab" — all length 3 |');
push('| "bbbbb" | 1 | Just a single "b" |');
push('| "pwwkew" | 3 | "wke" is length 3; "pwke" is a subsequence, not substring |');
push('| "dvdf" | 3 | "vdf" is length 3 |');
push('');
push('### Constraints');
push('- 0 to 50,000 characters');
push('- Letters (a-z, A-Z) and digits (0-9)');
push('');
push('### Approach');
push('');
push('**Brute force:** Check every substring and verify uniqueness — O(n³).');
push('');
push('**Sliding window solution (optimal):**');
push('');
push('Maintain a window that always has unique characters. When we find a repeat, shrink from the left until the repeat is gone.');
push('');
push('```text');
push('FUNCTION length_of_longest_substring(s):');
push('    char_set = EMPTY SET');
push('    left = 0');
push('    max_len = 0');
push('');
push('    FOR right FROM 0 TO length(s)-1:');
push('        WHILE s[right] IS IN char_set:');
push('            REMOVE s[left] FROM char_set');
push('            left = left + 1');
push('');
push('        ADD s[right] TO char_set');
push('        max_len = MAX(max_len, right - left + 1)');
push('');
push('    RETURN max_len');
push('```');
push('');
push('**Trace on "abcabcbb":**');
push('');
push('```');
push('right=0, a, set={a},        max=1');
push('right=1, b, set={a,b},      max=2');
push('right=2, c, set={a,b,c},    max=3');
push('right=3, a — repeat! shrink left to 1, set={b,c,a}, max=3');
push('right=4, b — repeat! shrink left to 2, set={c,a,b}, max=3');
push('right=5, c — repeat! shrink left to 3, set={a,b,c}, max=3');
push('right=6, b — repeat! shrink left to 5, set={c,b},   max=3');
push('right=7, b — repeat! shrink left to 7, set={b},     max=3');
push('```');
push('');
push('**Complexity:**');
push('- Time: O(n) — each char added once, removed at most once');
push('- Space: O(min(m, n)) — effectively O(1) since alphabet is bounded');
push('');
push('### Code Solution');
push('');
push('```python');
push('def length_of_longest_substring(s):');
push('    char_set = set()');
push('    left = 0');
push('    max_len = 0');
push('');
push('    for right in range(len(s)):');
push('        while s[right] in char_set:');
push('            char_set.remove(s[left])');
push('            left += 1');
push('');
push('        char_set.add(s[right])');
push('        max_len = max(max_len, right - left + 1)');
push('');
push('    return max_len');
push('```');
push('');
push('```javascript');
push('function lengthOfLongestSubstring(s) {');
push('    const charSet = new Set();');
push('    let left = 0;');
push('    let maxLen = 0;');
push('');
push('    for (let right = 0; right < s.length; right++) {');
push('        while (charSet.has(s[right])) {');
push('            charSet.delete(s[left]);');
push('            left++;');
push('        }');
push('');
push('        charSet.add(s[right]);');
push('        maxLen = Math.max(maxLen, right - left + 1);');
push('    }');
push('');
push('    return maxLen;');
push('}');
push('```');
push('');
hr();

// --- Problem 4: Subarray Sum Equals K ---
push('## 3.4 Subarray Sum Equals K');
push('');
push('| | |');
push('|---|---|');
push('| **Difficulty** | Medium |');
push('| **Subtopic** | Prefix Sum |');
push('| **Companies** | Amazon, Google, Microsoft, Facebook, Uber |');
push('');
push('### Problem Statement');
push('');
push('Given an array of integers (positive, negative, or zero) and a target `k`, count how many **contiguous subarrays** sum to exactly `k`.');
push('');
push('```');
push('Input:  arr = [1, 1, 1], k = 2');
push('Output: 2  (subarrays [1,1] at indices 0-1 and [1,1] at indices 1-2)');
push('```');
push('');
push('### Examples');
push('');
push('| Input | Output | Explanation |');
push('|---|---|---|');
push('| [1, 1, 1], k=2 | 2 | Two subarrays: [0,1] and [1,2] |');
push('| [1, 2, 3], k=3 | 2 | [0,1] = 1+2 and [2,2] = 3 |');
push('| [3,4,7,2,-3,1,4,2], k=7 | 4 | Four subarrays sum to 7 |');
push('');
push('### Constraints');
push('- 1 to 20,000 elements');
push('- Each element: -1000 to 1000');
push('- k: -10⁷ to 10⁷');
push('');
push('### Approach');
push('');
push('**Brute force:** Check every subarray — O(n²). For 20,000 elements, that\'s 200 million subarrays.');
push('');
push('**Prefix sum + hash map (optimal):**');
push('');
push('The key formula: sum(i, j) = prefix[j+1] - prefix[i]. If sum(i, j) = k, then prefix[j+1] - k = prefix[i].');
push('');
push('This means: when we\'re at position j, if (current_prefix - k) has appeared before, a subarray ending at j sums to k.');
push('');
push('```text');
push('FUNCTION subarray_sum(arr, k):');
push('    prefix_map = {0: 1}    # Seed for subarrays starting at index 0');
push('    prefix_sum = 0');
push('    count = 0');
push('');
push('    FOR EACH num IN arr:');
push('        prefix_sum = prefix_sum + num');
push('');
push('        IF (prefix_sum - k) IS IN prefix_map:');
push('            count = count + prefix_map[prefix_sum - k]');
push('');
push('        prefix_map[prefix_sum] = prefix_map[prefix_sum] + 1');
push('');
push('    RETURN count');
push('```');
push('');
push('**Trace on [3, 4, 7, 2, -3, 1, 4, 2] with k = 7:**');
push('');
push('```');
push('Init: prefix=0, map={0:1}, count=0');
push('');
push('i=0, val=3: prefix=3,  check 3-7=-4  → not found, map={0:1, 3:1}');
push('i=1, val=4: prefix=7,  check 7-7=0   → found! count=1,  subarray [3,4]');
push('i=2, val=7: prefix=14, check 14-7=7  → found! count=2,  subarray [7]');
push('i=3, val=2: prefix=16, check 16-7=9  → not found');
push('i=4, val=-3: prefix=13, check 13-7=6  → not found');
push('i=5, val=1: prefix=14, check 14-7=7  → found! count=3,  subarray [7,2,-3,1]');
push('i=6, val=4: prefix=18, check 18-7=11 → not found');
push('i=7, val=2: prefix=20, check 20-7=13 → found! count=4,  subarray [1,4,2]');
push('```');
push('');
push('**Why seed with {0: 1}?** This handles subarrays that start from index 0. When prefix_sum - k = 0, it means the subarray from index 0 to the current position sums to k.');
push('');
push('**Complexity:**');
push('- Time: O(n) — single pass with O(1) hash map operations');
push('- Space: O(n) — hash map stores up to n+1 prefix sums');
push('');
push('### Code Solution');
push('');
push('```python');
push('def subarray_sum(arr, k):');
push('    prefix_map = {0: 1}');
push('    prefix_sum = 0');
push('    count = 0');
push('');
push('    for num in arr:');
push('        prefix_sum += num');
push('');
push('        if (prefix_sum - k) in prefix_map:');
push('            count += prefix_map[prefix_sum - k]');
push('');
push('        prefix_map[prefix_sum] = prefix_map.get(prefix_sum, 0) + 1');
push('');
push('    return count');
push('```');
push('');
push('```javascript');
push('function subarraySum(arr, k) {');
push('    const prefixMap = new Map();');
push('    prefixMap.set(0, 1);');
push('    let prefixSum = 0;');
push('    let count = 0;');
push('');
push('    for (const num of arr) {');
push('        prefixSum += num;');
push('');
push('        if (prefixMap.has(prefixSum - k)) {');
push('            count += prefixMap.get(prefixSum - k);');
push('        }');
push('');
push('        prefixMap.set(prefixSum, (prefixMap.get(prefixSum) || 0) + 1);');
push('    }');
push('');
push('    return count;');
push('}');
push('```');
push('');
hr();

// ─── FOOTER ───
push('---');
push('');
push('*Happy coding! — TheWebytes DSA Team*');

// Write
fs.writeFileSync('dsa-content/doc.md', lines.join('\n'), 'utf8');
console.log('Wrote doc.md —', lines.join('\n').length, 'chars,', lines.length, 'lines');
